export const GET_POP_COURSES="GET_POP_COURSES"
export const GET_ONE_COURSE="GET_ONE_COURSE"
export const GET_INSTRUCTOR_COURSES="GET_INSTRUCTOR_COURSES"
export const GET_CATEGORY_COURSES="GET_CATEGORY_COURSES"